name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
    inputs:
      release-type:
        description: "Semver version bump type"
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Get variables
        id: get-vars
        run: |
          echo "playwright-version=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')" >> "$GITHUB_OUTPUT"
          echo "pkg-name=$(npm pkg get name | tr -d \")" >> "$GITHUB_OUTPUT"
          echo "pkg-version=$(npm pkg get version | sed 's/-.\+//' | tr -d \")" >> "$GITHUB_OUTPUT"
          echo "short-sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.get-vars.outputs.playwright-version }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        # currently `playwright.config.ts` only uses chromium, but eventually
        # it'd probably be worth `npx playwright install` to get all supported browsers
        run: npx playwright install chromium

      - name: Lint
        run: npm run lint

      - name: Bump package.json version
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          npm version ${{ inputs.release-type || format('{0}-{1}', steps.get-vars.outputs.pkg-version, steps.get-vars.outputs.short-sha) }}

      - name: Build extension
        id: build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Save Playwright results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Save extension zip
        uses: actions/upload-artifact@v3
        if: steps.build.outcome == 'success'
        with:
          name: ${{ steps.get-vars.outputs.pkg-name }}-${{ steps.get-vars.outputs.short-sha }}
          path: dist/

      - uses: actions/cache/save@v3
        if: ${{ inputs.release-type }}
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.run_id }}-${{ github.run_attempt }}
