name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
    inputs:
      release-type:
        description: "Semver version bump type"
        type: choice
        default: none
        options:
          - none (build only)
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Bump package.json version (only for releases)
        if: inputs.release-type && inputs.release-type != 'none'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          npm version ${{ inputs.release-type }}

      - name: Get variables
        id: get-vars
        run: |
          echo "playwright-version=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')" >> "$GITHUB_OUTPUT"
          echo "pkg-name=$(npm pkg get name | tr -d \")" >> "$GITHUB_OUTPUT"
          echo "short-sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.get-vars.outputs.playwright-version }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        # currently `playwright.config.ts` only uses chromium, but eventually
        # it'd probably be worth `npx playwright install` to get all supported browsers
        run: npx playwright install chromium

      - name: Lint
        run: npm run lint

      - name: Build extension
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Save Playwright results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Save extension zip
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get-vars.outputs.pkg-name }}-${{ steps.get-vars.outputs.short-sha }}
          path: dist/

      - name: Push tags (only for releases)
        if: inputs.release-type && inputs.release-type != 'none'
        uses: ad-m/github-push-action@v0.6.0
        with:
          tags: true
