name: Release

on:
  push:
  # workflow_dispatch:
  #   inputs:
  #     release-type:
  #       description: "Semver version bump type"
  #       type: choice
  #       required: true
  #       options:
  #         - patch
  #         - minor
  #         - major

jobs:
  # build:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     release-type: ${{ inputs.release-type }}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/cache/restore@v3
      #   id: restore-cache
      #   with:
      #     path: ${{ github.workspace }}
      #     key: workspace-${{ github.run_id }}-${{ github.run_attempt }}
      #     fail-on-cache-miss: true

      - name: Push version bump + tags
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push
