name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Semver version bump type"
        type: choice
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release-type: ${{ inputs.release-type }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: Push tags
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}
          tags: true
